import InvokeEnumerateAzureSubDomains
import InvokeEnumerateAzureBlobs

InvokeEnumerateAzureSubDomains.enumerateAzureSubDomains("retailcorp","permutations.txt")
InvokeEnumerateAzureBlobs.enumerateAzureBlobs("retailcorp")
